import 'dotenv/config'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'

const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
    ssl: { rejectUnauthorized: false }
})
const prisma = new PrismaClient({ adapter })

const recipes = [
    // ─── BREAKFAST ───────────────────────────────────────────────────
    {
        title: 'Turkish Eggs (Çılbır)',
        description: 'Silky poached eggs on whipped garlic yogurt, finished with paprika butter. A classic Turkish breakfast.',
        category: 'Breakfast',
        prepTime: 5,
        cookTime: 10,
        servings: 2,
        tags: 'Turkish,High-Protein,Vegetarian',
        ingredients: [
            { name: 'Greek yogurt', amount: '400', unit: 'g' },
            { name: 'Eggs', amount: '4', unit: '' },
            { name: 'Butter', amount: '2', unit: 'tbsp' },
            { name: 'Smoked paprika', amount: '1', unit: 'tsp' },
            { name: 'Chili flakes', amount: '0.5', unit: 'tsp' },
            { name: 'Garlic', amount: '1', unit: 'clove' },
            { name: 'White vinegar', amount: '1', unit: 'tbsp' },
            { name: 'Fresh dill', amount: '1', unit: 'tbsp' },
        ],
        steps: [
            { order: 1, instruction: 'Whip yogurt with crushed garlic and a pinch of salt until smooth. Spread onto two plates and warm slightly.' },
            { order: 2, instruction: 'Bring a pan of water to a gentle simmer with the vinegar. Poach eggs for 3 minutes until whites are set but yolks are runny.' },
            { order: 3, instruction: 'Melt butter in a small pan over medium heat, add paprika and chili flakes, swirl for 30 seconds until fragrant and deep orange.' },
            { order: 4, instruction: 'Place two poached eggs on each yogurt bed, drizzle generously with the paprika butter, garnish with dill and serve immediately with crusty bread.' },
        ],
    },
    {
        title: 'Japanese Tamagoyaki',
        description: 'Sweetened rolled omelette — a Japanese breakfast staple that is high in protein and ready in minutes.',
        category: 'Breakfast',
        prepTime: 5,
        cookTime: 10,
        servings: 2,
        tags: 'Japanese,High-Protein,Low-Carb',
        ingredients: [
            { name: 'Eggs', amount: '4', unit: '' },
            { name: 'Dashi stock', amount: '2', unit: 'tbsp' },
            { name: 'Soy sauce', amount: '1', unit: 'tsp' },
            { name: 'Sugar', amount: '1', unit: 'tsp' },
            { name: 'Mirin', amount: '1', unit: 'tsp' },
            { name: 'Sesame oil', amount: '0.5', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Whisk eggs with dashi, soy sauce, sugar, and mirin until fully combined.' },
            { order: 2, instruction: 'Heat sesame oil in a tamagoyaki pan or small non-stick skillet over medium heat.' },
            { order: 3, instruction: 'Pour in one-third of the egg mixture and tilt to coat the pan. When just set, roll it to one end using a spatula or chopsticks.' },
            { order: 4, instruction: 'Push the roll to the far end, add another third of the egg, lift the roll to let egg flow underneath, then roll again.' },
            { order: 5, instruction: 'Repeat with remaining egg. The finished roll should be golden outside and layered inside. Slice into rounds and serve.' },
        ],
    },
    {
        title: 'Huevos Rancheros',
        description: 'Mexican ranch-style eggs on crispy tortillas with smoky tomato salsa and black beans. Bold, filling, high-protein.',
        category: 'Breakfast',
        prepTime: 10,
        cookTime: 15,
        servings: 2,
        tags: 'Mexican,High-Protein,Spicy',
        ingredients: [
            { name: 'Eggs', amount: '4', unit: '' },
            { name: 'Corn tortillas', amount: '4', unit: '' },
            { name: 'Canned tomatoes', amount: '400', unit: 'g' },
            { name: 'Black beans', amount: '1', unit: 'can' },
            { name: 'Jalapeño', amount: '1', unit: '' },
            { name: 'Onion', amount: '0.5', unit: '' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
            { name: 'Cumin', amount: '1', unit: 'tsp' },
            { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            { name: 'Fresh coriander', amount: '1', unit: 'handful' },
        ],
        steps: [
            { order: 1, instruction: 'Sauté diced onion and jalapeño in olive oil for 3 minutes. Add garlic and cumin, cook 1 minute.' },
            { order: 2, instruction: 'Add canned tomatoes, season with salt, and simmer 8 minutes until slightly thickened.' },
            { order: 3, instruction: 'Warm and lightly crisp tortillas in a dry pan. Heat drained black beans in a small pot with a pinch of cumin.' },
            { order: 4, instruction: 'Make four wells in the salsa and crack an egg into each. Cover and cook 4–5 minutes until whites are set.' },
            { order: 5, instruction: 'Serve eggs and salsa over tortillas with black beans alongside. Top with fresh coriander.' },
        ],
    },
    {
        title: 'High-Protein Banana Pancakes',
        description: 'Two-ingredient base with protein powder and oats — fluffy, naturally sweet pancakes with 30g protein per serve.',
        category: 'Breakfast',
        prepTime: 5,
        cookTime: 15,
        servings: 2,
        tags: 'High-Protein,Gluten-Free,Meal Prep',
        ingredients: [
            { name: 'Ripe bananas', amount: '2', unit: '' },
            { name: 'Eggs', amount: '4', unit: '' },
            { name: 'Rolled oats', amount: '60', unit: 'g' },
            { name: 'Vanilla protein powder', amount: '30', unit: 'g' },
            { name: 'Baking powder', amount: '0.5', unit: 'tsp' },
            { name: 'Cinnamon', amount: '0.5', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Blend oats into a fine flour. Add bananas, eggs, protein powder, baking powder, and cinnamon and blend until smooth.' },
            { order: 2, instruction: 'Let batter rest 2 minutes — it will thicken slightly.' },
            { order: 3, instruction: 'Heat a non-stick pan over medium-low heat, lightly grease. Pour ¼ cup batter per pancake.' },
            { order: 4, instruction: 'Cook 2–3 minutes until bubbles form on the surface and edges look set. Flip and cook 1–2 minutes more.' },
            { order: 5, instruction: 'Serve stacked with Greek yogurt, fresh fruit, or a drizzle of honey.' },
        ],
    },
    {
        title: 'Smoked Salmon & Avocado Toast',
        description: 'Omega-3 rich smoked salmon on sourdough with creamy avocado and capers — a high-protein breakfast in under 15 minutes.',
        category: 'Breakfast',
        prepTime: 10,
        cookTime: 5,
        servings: 2,
        tags: 'High-Protein,Omega-3,Healthy Fats',
        ingredients: [
            { name: 'Sourdough bread', amount: '4', unit: 'slices' },
            { name: 'Smoked salmon', amount: '150', unit: 'g' },
            { name: 'Avocado', amount: '1', unit: '' },
            { name: 'Cream cheese', amount: '50', unit: 'g' },
            { name: 'Lemon', amount: '0.5', unit: '' },
            { name: 'Capers', amount: '1', unit: 'tbsp' },
            { name: 'Red onion', amount: '0.25', unit: '' },
            { name: 'Everything bagel seasoning', amount: '1', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Toast sourdough until golden and crisp.' },
            { order: 2, instruction: 'Mash avocado with a squeeze of lemon and a pinch of salt.' },
            { order: 3, instruction: 'Spread cream cheese on each slice, then add smashed avocado.' },
            { order: 4, instruction: 'Lay smoked salmon on top, scatter capers and thinly sliced red onion.' },
            { order: 5, instruction: 'Finish with everything bagel seasoning and a final squeeze of lemon.' },
        ],
    },

    // ─── LUNCH ────────────────────────────────────────────────────────
    {
        title: 'Thai Larb Gai',
        description: 'Bright, herby Thai minced chicken salad with toasted rice powder and lime. Served at room temperature — great for meal prep.',
        category: 'Lunch',
        prepTime: 15,
        cookTime: 10,
        servings: 2,
        tags: 'Thai,High-Protein,Low-Carb,Spicy',
        ingredients: [
            { name: 'Ground chicken', amount: '400', unit: 'g' },
            { name: 'Shallots', amount: '3', unit: '' },
            { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
            { name: 'Lime juice', amount: '3', unit: 'tbsp' },
            { name: 'Toasted rice powder', amount: '2', unit: 'tbsp' },
            { name: 'Dried chili flakes', amount: '1', unit: 'tsp' },
            { name: 'Fresh mint', amount: '1', unit: 'handful' },
            { name: 'Fresh coriander', amount: '1', unit: 'handful' },
            { name: 'Spring onions', amount: '3', unit: '' },
        ],
        steps: [
            { order: 1, instruction: 'Toast uncooked rice in a dry pan until golden, then grind to a coarse powder in a mortar.' },
            { order: 2, instruction: 'Cook ground chicken in a pan over medium-high heat with 1 tbsp water, breaking into fine pieces, until just cooked through.' },
            { order: 3, instruction: 'Remove from heat and add fish sauce, lime juice, and chili flakes. Toss well.' },
            { order: 4, instruction: 'Add sliced shallots, spring onions, mint, coriander, and toasted rice powder. Toss again.' },
            { order: 5, instruction: 'Taste and adjust fish sauce/lime balance. Serve with lettuce cups, sticky rice, or cucumber.' },
        ],
    },
    {
        title: 'Korean Bibimbap',
        description: 'Vibrant Korean rice bowl topped with seasoned vegetables, spiced beef, a fried egg, and gochujang sauce.',
        category: 'Lunch',
        prepTime: 20,
        cookTime: 20,
        servings: 2,
        tags: 'Korean,High-Protein,Balanced',
        ingredients: [
            { name: 'Cooked white rice', amount: '300', unit: 'g' },
            { name: 'Beef mince', amount: '200', unit: 'g' },
            { name: 'Baby spinach', amount: '100', unit: 'g' },
            { name: 'Carrot', amount: '1', unit: '' },
            { name: 'Zucchini', amount: '1', unit: '' },
            { name: 'Eggs', amount: '2', unit: '' },
            { name: 'Gochujang paste', amount: '2', unit: 'tbsp' },
            { name: 'Sesame oil', amount: '2', unit: 'tbsp' },
            { name: 'Soy sauce', amount: '2', unit: 'tbsp' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
        ],
        steps: [
            { order: 1, instruction: 'Brown beef mince with 1 tbsp soy sauce and minced garlic. Set aside.' },
            { order: 2, instruction: 'Sauté julienned carrot in sesame oil 3 minutes. Repeat with zucchini. Wilt spinach with a pinch of salt.' },
            { order: 3, instruction: 'Fry eggs sunny-side up in sesame oil.' },
            { order: 4, instruction: 'Divide warm rice into bowls. Arrange beef and all vegetables in sections around the bowl.' },
            { order: 5, instruction: 'Top each bowl with a fried egg and a generous dollop of gochujang. Mix everything together before eating.' },
        ],
    },
    {
        title: 'Greek Chicken Souvlaki Wraps',
        description: 'Lemon-herb marinated chicken on warm pita with tzatziki, tomato, and onion — a high-protein Mediterranean classic.',
        category: 'Lunch',
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        tags: 'Greek,High-Protein,Meal Prep',
        ingredients: [
            { name: 'Chicken breast', amount: '400', unit: 'g' },
            { name: 'Pita bread', amount: '4', unit: '' },
            { name: 'Greek yogurt', amount: '150', unit: 'g' },
            { name: 'Cucumber', amount: '0.5', unit: '' },
            { name: 'Tomato', amount: '1', unit: '' },
            { name: 'Red onion', amount: '0.5', unit: '' },
            { name: 'Olive oil', amount: '2', unit: 'tbsp' },
            { name: 'Lemon', amount: '1', unit: '' },
            { name: 'Dried oregano', amount: '1', unit: 'tsp' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
        ],
        steps: [
            { order: 1, instruction: 'Cube chicken and marinate 10 minutes in olive oil, lemon juice, oregano, minced garlic, salt and pepper.' },
            { order: 2, instruction: 'Make tzatziki: grate and squeeze cucumber dry, mix with yogurt, 1 garlic clove, and a squeeze of lemon.' },
            { order: 3, instruction: 'Thread chicken onto skewers (or just pan-fry). Cook over high heat 10–12 minutes, turning, until golden and cooked through.' },
            { order: 4, instruction: 'Warm pitas in a dry pan or directly over a gas flame for 30 seconds per side.' },
            { order: 5, instruction: 'Spread tzatziki on pita, add chicken, sliced tomato, red onion, and wrap tightly.' },
        ],
    },
    {
        title: 'Vietnamese Beef Pho',
        description: 'Aromatic spiced beef broth with rice noodles, thin-sliced sirloin, and fresh herbs. Comfort in a bowl.',
        category: 'Lunch',
        prepTime: 20,
        cookTime: 30,
        servings: 2,
        tags: 'Vietnamese,High-Protein,Low-Fat',
        ingredients: [
            { name: 'Beef sirloin', amount: '300', unit: 'g' },
            { name: 'Rice noodles', amount: '200', unit: 'g' },
            { name: 'Beef stock', amount: '1.5', unit: 'L' },
            { name: 'Star anise', amount: '3', unit: '' },
            { name: 'Cinnamon stick', amount: '1', unit: '' },
            { name: 'Fresh ginger', amount: '50', unit: 'g' },
            { name: 'Onion', amount: '1', unit: '' },
            { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
            { name: 'Bean sprouts', amount: '100', unit: 'g' },
            { name: 'Fresh basil & lime', amount: '1', unit: 'handful' },
        ],
        steps: [
            { order: 1, instruction: 'Char the halved onion and ginger directly over a flame or under a broiler until lightly blackened.' },
            { order: 2, instruction: 'Bring stock to a simmer with charred onion, ginger, star anise, cinnamon, and fish sauce. Simmer 20 minutes. Strain.' },
            { order: 3, instruction: 'Soak rice noodles in hot water 10 minutes until tender. Drain and divide between bowls.' },
            { order: 4, instruction: 'Freeze the sirloin 20 minutes for easier slicing, then slice paper-thin against the grain.' },
            { order: 5, instruction: 'Ladle boiling broth into bowls over the noodles — this cooks the raw beef. Top with bean sprouts, basil, and lime.' },
        ],
    },
    {
        title: 'Turkish Red Lentil Soup',
        description: 'Silky, warmly spiced red lentil soup (mercimek çorbası) with a paprika butter finish. Vegan, cheap, and protein-rich.',
        category: 'Lunch',
        prepTime: 10,
        cookTime: 25,
        servings: 4,
        tags: 'Turkish,High-Protein,Vegan,Meal Prep',
        ingredients: [
            { name: 'Red lentils', amount: '250', unit: 'g' },
            { name: 'Onion', amount: '1', unit: '' },
            { name: 'Carrot', amount: '1', unit: '' },
            { name: 'Tomato paste', amount: '2', unit: 'tbsp' },
            { name: 'Cumin', amount: '2', unit: 'tsp' },
            { name: 'Smoked paprika', amount: '1', unit: 'tsp' },
            { name: 'Olive oil', amount: '2', unit: 'tbsp' },
            { name: 'Vegetable stock', amount: '1.2', unit: 'L' },
            { name: 'Lemon', amount: '1', unit: '' },
            { name: 'Dried mint', amount: '1', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Sauté diced onion and carrot in olive oil 5 minutes until softened. Add tomato paste and cumin, cook 2 minutes.' },
            { order: 2, instruction: 'Add rinsed lentils and stock. Bring to a boil, skim any foam, then simmer 20 minutes until lentils are very soft.' },
            { order: 3, instruction: 'Blend smooth with an immersion blender. Add more water if too thick. Season with salt and lemon juice.' },
            { order: 4, instruction: 'For the finish: heat olive oil with paprika and dried mint until sizzling, pour swirl over each bowl.' },
            { order: 5, instruction: 'Serve with crusty bread and extra lemon wedges.' },
        ],
    },

    // ─── DINNER ──────────────────────────────────────────────────────
    {
        title: 'Moroccan Chicken Tagine',
        description: 'Slow-braised chicken with preserved lemon, olives, and ras el hanout. Fragrant North African comfort food.',
        category: 'Dinner',
        prepTime: 15,
        cookTime: 50,
        servings: 4,
        tags: 'Moroccan,High-Protein,Meal Prep',
        ingredients: [
            { name: 'Chicken thighs', amount: '800', unit: 'g' },
            { name: 'Onion', amount: '2', unit: '' },
            { name: 'Garlic', amount: '4', unit: 'cloves' },
            { name: 'Preserved lemon', amount: '1', unit: '' },
            { name: 'Green olives', amount: '100', unit: 'g' },
            { name: 'Canned tomatoes', amount: '400', unit: 'g' },
            { name: 'Chickpeas', amount: '1', unit: 'can' },
            { name: 'Ras el hanout', amount: '2', unit: 'tsp' },
            { name: 'Ground cumin', amount: '1', unit: 'tsp' },
            { name: 'Olive oil', amount: '2', unit: 'tbsp' },
            { name: 'Fresh coriander', amount: '1', unit: 'handful' },
        ],
        steps: [
            { order: 1, instruction: 'Brown chicken thighs in olive oil over high heat, 3 minutes per side. Remove and set aside.' },
            { order: 2, instruction: 'In the same pan, sauté sliced onions 5 minutes. Add garlic, ras el hanout, and cumin, cook 2 minutes.' },
            { order: 3, instruction: 'Add tomatoes, chickpeas, olives, and chopped preserved lemon (rind only). Return chicken on top.' },
            { order: 4, instruction: 'Cover and simmer on low heat 35–40 minutes until chicken is very tender and sauce is rich.' },
            { order: 5, instruction: 'Scatter fresh coriander and serve with couscous or flatbread.' },
        ],
    },
    {
        title: 'Butter Chicken (Murgh Makhani)',
        description: 'Tender chicken in a creamy tomato-butter sauce spiced with garam masala and ginger. The definitive Indian comfort dish.',
        category: 'Dinner',
        prepTime: 20,
        cookTime: 35,
        servings: 4,
        tags: 'Indian,High-Protein,Creamy',
        ingredients: [
            { name: 'Chicken breast', amount: '700', unit: 'g' },
            { name: 'Butter', amount: '3', unit: 'tbsp' },
            { name: 'Onion', amount: '2', unit: '' },
            { name: 'Garlic', amount: '4', unit: 'cloves' },
            { name: 'Fresh ginger', amount: '30', unit: 'g' },
            { name: 'Canned tomatoes', amount: '400', unit: 'g' },
            { name: 'Heavy cream', amount: '100', unit: 'ml' },
            { name: 'Garam masala', amount: '2', unit: 'tsp' },
            { name: 'Paprika', amount: '1', unit: 'tsp' },
            { name: 'Turmeric', amount: '0.5', unit: 'tsp' },
            { name: 'Cumin', amount: '1', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Cube chicken and marinate 10 minutes in yogurt, garam masala, turmeric, and salt. Grill or pan-fry until lightly charred. Set aside.' },
            { order: 2, instruction: 'Melt butter in a deep pan. Sauté onions until deep golden, 10 minutes. Add garlic and ginger paste, cook 3 minutes.' },
            { order: 3, instruction: 'Add tomatoes, paprika, cumin, and remaining garam masala. Simmer 15 minutes. Blend smooth.' },
            { order: 4, instruction: 'Return sauce to pan, add cream and chicken. Simmer 10 minutes. Adjust salt and add a final tablespoon of butter for richness.' },
            { order: 5, instruction: 'Serve with basmati rice and naan, garnished with a swirl of cream and fresh coriander.' },
        ],
    },
    {
        title: 'Spanish Chicken Paella',
        description: 'Saffron-scented rice with golden chicken and sweet peppers, cooked in one pan for a true Spanish feast.',
        category: 'Dinner',
        prepTime: 15,
        cookTime: 45,
        servings: 4,
        tags: 'Spanish,High-Protein,One-Pan',
        ingredients: [
            { name: 'Chicken thighs', amount: '600', unit: 'g' },
            { name: 'Paella rice', amount: '300', unit: 'g' },
            { name: 'Chicken stock', amount: '900', unit: 'ml' },
            { name: 'Saffron', amount: '1', unit: 'pinch' },
            { name: 'Onion', amount: '1', unit: '' },
            { name: 'Red bell pepper', amount: '1', unit: '' },
            { name: 'Garlic', amount: '3', unit: 'cloves' },
            { name: 'Tomatoes', amount: '2', unit: '' },
            { name: 'Smoked paprika', amount: '2', unit: 'tsp' },
            { name: 'Olive oil', amount: '3', unit: 'tbsp' },
            { name: 'Frozen peas', amount: '100', unit: 'g' },
        ],
        steps: [
            { order: 1, instruction: 'Steep saffron in 2 tbsp warm stock. Brown chicken thighs in olive oil in a wide pan, 4 minutes each side. Remove.' },
            { order: 2, instruction: 'Sauté onion and pepper 5 minutes. Add garlic, grated tomatoes, and paprika, cook 5 minutes until jammy.' },
            { order: 3, instruction: 'Add rice and stir to coat in the sofrito. Pour in stock and saffron water, season well. Nestle chicken on top.' },
            { order: 4, instruction: 'Bring to a boil then reduce to medium-low. Cook uncovered 18–20 minutes — do not stir. Add peas in the last 5 minutes.' },
            { order: 5, instruction: 'When liquid is absorbed and rice is tender, remove from heat, cover with foil for 5 minutes. Serve with lemon wedges.' },
        ],
    },
    {
        title: 'Teriyaki Salmon',
        description: 'Caramelised teriyaki-glazed salmon ready in 20 minutes — sticky, sweet, and packed with omega-3.',
        category: 'Dinner',
        prepTime: 5,
        cookTime: 15,
        servings: 2,
        tags: 'Japanese,High-Protein,Omega-3,Quick',
        ingredients: [
            { name: 'Salmon fillets', amount: '2', unit: '(150g each)' },
            { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
            { name: 'Honey', amount: '2', unit: 'tbsp' },
            { name: 'Mirin', amount: '2', unit: 'tbsp' },
            { name: 'Garlic', amount: '1', unit: 'clove' },
            { name: 'Fresh ginger', amount: '10', unit: 'g' },
            { name: 'Sesame seeds', amount: '1', unit: 'tsp' },
            { name: 'Spring onions', amount: '2', unit: '' },
        ],
        steps: [
            { order: 1, instruction: 'Mix soy sauce, honey, mirin, minced garlic, and grated ginger for the teriyaki sauce.' },
            { order: 2, instruction: 'Pat salmon dry and season lightly. Heat oil in a non-stick pan over medium-high heat.' },
            { order: 3, instruction: 'Cook salmon skin-side down 4 minutes until crispy. Flip and cook 2 minutes more.' },
            { order: 4, instruction: 'Pour in the teriyaki sauce. Reduce heat to medium and spoon sauce over salmon as it thickens, about 2 minutes.' },
            { order: 5, instruction: 'Serve over steamed rice, garnished with sesame seeds and sliced spring onions.' },
        ],
    },
    {
        title: 'Kung Pao Chicken',
        description: 'Sichuan-style stir-fry with tender chicken, crunchy peanuts, and dried chilies in a tangy-spicy sauce.',
        category: 'Dinner',
        prepTime: 15,
        cookTime: 15,
        servings: 3,
        tags: 'Chinese,High-Protein,Spicy,Quick',
        ingredients: [
            { name: 'Chicken breast', amount: '500', unit: 'g' },
            { name: 'Roasted peanuts', amount: '80', unit: 'g' },
            { name: 'Dried red chilies', amount: '8', unit: '' },
            { name: 'Spring onions', amount: '4', unit: '' },
            { name: 'Garlic', amount: '3', unit: 'cloves' },
            { name: 'Fresh ginger', amount: '15', unit: 'g' },
            { name: 'Soy sauce', amount: '2', unit: 'tbsp' },
            { name: 'Hoisin sauce', amount: '1', unit: 'tbsp' },
            { name: 'Rice vinegar', amount: '1', unit: 'tbsp' },
            { name: 'Cornstarch', amount: '1', unit: 'tbsp' },
            { name: 'Sesame oil', amount: '1', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Cube chicken and toss with cornstarch, 1 tbsp soy sauce, and a pinch of salt. Marinate 5 minutes.' },
            { order: 2, instruction: 'Mix remaining soy sauce, hoisin, rice vinegar, and sesame oil for the sauce.' },
            { order: 3, instruction: 'Stir-fry chicken in very hot oil until golden and cooked through, about 4 minutes. Remove.' },
            { order: 4, instruction: 'In the same wok, fry dried chilies 30 seconds, then add garlic and ginger and toss 30 seconds.' },
            { order: 5, instruction: 'Return chicken, pour in sauce, add peanuts and spring onions, toss everything 1 minute. Serve over rice.' },
        ],
    },
    {
        title: 'Lebanese Kafta with Bulgur',
        description: 'Spiced ground beef kafta skewers with fluffy bulgur pilaf and yogurt sauce — high-protein Middle Eastern dinner.',
        category: 'Dinner',
        prepTime: 20,
        cookTime: 20,
        servings: 4,
        tags: 'Lebanese,High-Protein,Middle Eastern',
        ingredients: [
            { name: 'Ground beef', amount: '600', unit: 'g' },
            { name: 'Bulgur wheat', amount: '200', unit: 'g' },
            { name: 'Onion', amount: '1', unit: '' },
            { name: 'Fresh parsley', amount: '1', unit: 'handful' },
            { name: 'Cinnamon', amount: '0.5', unit: 'tsp' },
            { name: 'Ground cumin', amount: '1', unit: 'tsp' },
            { name: 'Paprika', amount: '1', unit: 'tsp' },
            { name: 'Allspice', amount: '0.5', unit: 'tsp' },
            { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            { name: 'Plain yogurt', amount: '200', unit: 'g' },
        ],
        steps: [
            { order: 1, instruction: 'Cook bulgur: pour boiling salted water over bulgur, cover and let stand 15 minutes. Fluff with a fork.' },
            { order: 2, instruction: 'Mix ground beef with grated onion, chopped parsley, cinnamon, cumin, paprika, allspice, and salt until combined.' },
            { order: 3, instruction: 'Shape mixture around skewers into oval logs, pressing firmly so they hold.' },
            { order: 4, instruction: 'Grill or pan-fry kafta over high heat 4–5 minutes per side until nicely charred and cooked through.' },
            { order: 5, instruction: 'Serve kafta over bulgur with yogurt on the side and a tomato-cucumber salad.' },
        ],
    },
    {
        title: 'Italian Chicken Piccata',
        description: 'Pan-fried chicken in a bright lemon-caper butter sauce. An Italian restaurant classic that takes 30 minutes.',
        category: 'Dinner',
        prepTime: 10,
        cookTime: 20,
        servings: 4,
        tags: 'Italian,High-Protein,Quick',
        ingredients: [
            { name: 'Chicken breasts', amount: '600', unit: 'g' },
            { name: 'Butter', amount: '3', unit: 'tbsp' },
            { name: 'Capers', amount: '2', unit: 'tbsp' },
            { name: 'Lemons', amount: '2', unit: '' },
            { name: 'Dry white wine', amount: '100', unit: 'ml' },
            { name: 'Chicken stock', amount: '150', unit: 'ml' },
            { name: 'Plain flour', amount: '30', unit: 'g' },
            { name: 'Fresh parsley', amount: '1', unit: 'handful' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
            { name: 'Olive oil', amount: '2', unit: 'tbsp' },
        ],
        steps: [
            { order: 1, instruction: 'Butterfly chicken breasts and pound to 1cm thick. Season and dust both sides lightly with flour.' },
            { order: 2, instruction: 'Heat olive oil and 1 tbsp butter in a wide pan over high heat. Cook chicken 3–4 minutes per side until golden. Remove.' },
            { order: 3, instruction: 'Deglaze pan with white wine, scraping up browned bits. Add sliced garlic, cook 1 minute.' },
            { order: 4, instruction: 'Add stock, lemon juice, and capers. Simmer 4 minutes to reduce by a third.' },
            { order: 5, instruction: 'Remove from heat, whisk in remaining butter. Return chicken to coat in the sauce. Garnish with parsley and lemon slices.' },
        ],
    },

    // ─── SNACK ───────────────────────────────────────────────────────
    {
        title: 'High-Protein Hummus',
        description: 'Extra-smooth hummus boosted with an additional can of chickpeas for double the protein. Perfect for meal prep.',
        category: 'Snack',
        prepTime: 10,
        cookTime: 0,
        servings: 6,
        tags: 'High-Protein,Vegan,Meal Prep,Middle Eastern',
        ingredients: [
            { name: 'Chickpeas', amount: '2', unit: 'cans' },
            { name: 'Tahini', amount: '3', unit: 'tbsp' },
            { name: 'Lemons', amount: '2', unit: '' },
            { name: 'Garlic', amount: '2', unit: 'cloves' },
            { name: 'Olive oil', amount: '3', unit: 'tbsp' },
            { name: 'Cumin', amount: '1', unit: 'tsp' },
            { name: 'Ice water', amount: '4', unit: 'tbsp' },
            { name: 'Paprika', amount: '0.5', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Drain and rinse chickpeas. Reserve a few for garnish. For extra-smooth hummus, remove the skins by pinching each one.' },
            { order: 2, instruction: 'Blend tahini, lemon juice, and garlic until pale and fluffy, about 1 minute.' },
            { order: 3, instruction: 'Add chickpeas, cumin, and salt. Blend 2 minutes, adding ice water a tablespoon at a time until ultra-smooth.' },
            { order: 4, instruction: 'Taste and adjust lemon and salt.' },
            { order: 5, instruction: 'Spread into a bowl, drizzle with olive oil, dust with paprika, and top with reserved chickpeas. Serve with pita or vegetables.' },
        ],
    },
    {
        title: 'Cottage Cheese & Berry Bowl',
        description: 'High-protein cottage cheese with fresh berries, walnuts, and honey — a quick snack with 20g of protein.',
        category: 'Snack',
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        tags: 'High-Protein,Low-Carb,Quick',
        ingredients: [
            { name: 'Cottage cheese', amount: '200', unit: 'g' },
            { name: 'Mixed berries', amount: '100', unit: 'g' },
            { name: 'Honey', amount: '1', unit: 'tsp' },
            { name: 'Walnuts', amount: '20', unit: 'g' },
            { name: 'Chia seeds', amount: '1', unit: 'tsp' },
            { name: 'Cinnamon', amount: '1', unit: 'pinch' },
        ],
        steps: [
            { order: 1, instruction: 'Spoon cottage cheese into a bowl.' },
            { order: 2, instruction: 'Top with berries, roughly chopped walnuts, and chia seeds.' },
            { order: 3, instruction: 'Drizzle with honey and finish with a pinch of cinnamon.' },
        ],
    },
    {
        title: 'Turkey & Cheese Roll-Ups',
        description: 'No-cook high-protein snack — turkey slices wrapped around cream cheese, cucumber, and bell pepper. Great for on the go.',
        category: 'Snack',
        prepTime: 5,
        cookTime: 0,
        servings: 2,
        tags: 'High-Protein,Low-Carb,Keto,Quick',
        ingredients: [
            { name: 'Turkey breast slices', amount: '150', unit: 'g' },
            { name: 'Cream cheese', amount: '50', unit: 'g' },
            { name: 'Cucumber', amount: '0.5', unit: '' },
            { name: 'Bell pepper', amount: '0.5', unit: '' },
            { name: 'Baby spinach', amount: '1', unit: 'handful' },
            { name: 'Everything bagel seasoning', amount: '0.5', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Lay turkey slices flat on a board.' },
            { order: 2, instruction: 'Spread a thin layer of cream cheese on each slice.' },
            { order: 3, instruction: 'Place a strip of cucumber, bell pepper, and a few spinach leaves at one end.' },
            { order: 4, instruction: 'Roll tightly, secure with a toothpick if needed, and dust with bagel seasoning.' },
        ],
    },
    {
        title: 'Edamame with Sea Salt & Chili',
        description: 'Steamed edamame tossed with sea salt, chili flakes, and sesame oil. A Japanese high-protein snack in under 10 minutes.',
        category: 'Snack',
        prepTime: 2,
        cookTime: 8,
        servings: 2,
        tags: 'Japanese,High-Protein,Vegan,Quick',
        ingredients: [
            { name: 'Frozen edamame in pods', amount: '300', unit: 'g' },
            { name: 'Sea salt', amount: '1', unit: 'tsp' },
            { name: 'Chili flakes', amount: '0.5', unit: 'tsp' },
            { name: 'Sesame oil', amount: '1', unit: 'tsp' },
            { name: 'Toasted sesame seeds', amount: '1', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Bring a pot of salted water to a boil. Add edamame and cook 5 minutes.' },
            { order: 2, instruction: 'Drain and pat dry.' },
            { order: 3, instruction: 'Toss immediately with sesame oil, sea salt, and chili flakes.' },
            { order: 4, instruction: 'Scatter sesame seeds over the top. Serve warm — eat by squeezing the beans out of the pods.' },
        ],
    },

    // ─── DESSERT ────────────────────────────────────────────────────
    {
        title: 'Protein Chocolate Mousse',
        description: 'Thick, airy chocolate mousse made with Greek yogurt and chocolate protein powder. Under 200 calories and 25g protein.',
        category: 'Dessert',
        prepTime: 10,
        cookTime: 0,
        servings: 2,
        tags: 'High-Protein,Low-Sugar,Quick,Chocolate',
        ingredients: [
            { name: 'Greek yogurt', amount: '250', unit: 'g' },
            { name: 'Chocolate protein powder', amount: '30', unit: 'g' },
            { name: 'Cocoa powder', amount: '2', unit: 'tbsp' },
            { name: 'Honey', amount: '1', unit: 'tbsp' },
            { name: 'Almond milk', amount: '30', unit: 'ml' },
            { name: 'Dark chocolate chips', amount: '20', unit: 'g' },
        ],
        steps: [
            { order: 1, instruction: 'Whisk together yogurt, protein powder, cocoa, honey, and almond milk until completely smooth and thick.' },
            { order: 2, instruction: 'Taste and adjust sweetness — add a little more honey or a pinch of salt to intensify the chocolate flavour.' },
            { order: 3, instruction: 'Spoon into glasses and refrigerate 30 minutes for a firmer set, or eat immediately for soft-serve texture.' },
            { order: 4, instruction: 'Top with dark chocolate chips and a light dusting of cocoa powder before serving.' },
        ],
    },
    {
        title: 'Greek Yogurt Bark with Berries',
        description: 'Frozen yogurt bark layered with honey, mixed berries, and granola — a high-protein dessert that keeps in the freezer for a week.',
        category: 'Dessert',
        prepTime: 10,
        cookTime: 0,
        servings: 4,
        tags: 'High-Protein,Low-Sugar,Frozen,Meal Prep',
        ingredients: [
            { name: 'Greek yogurt', amount: '500', unit: 'g' },
            { name: 'Honey', amount: '2', unit: 'tbsp' },
            { name: 'Mixed berries', amount: '150', unit: 'g' },
            { name: 'Granola', amount: '50', unit: 'g' },
            { name: 'Dark chocolate', amount: '30', unit: 'g' },
            { name: 'Vanilla extract', amount: '0.5', unit: 'tsp' },
        ],
        steps: [
            { order: 1, instruction: 'Line a baking tray with parchment paper.' },
            { order: 2, instruction: 'Mix yogurt with honey and vanilla. Spread in an even layer about 1cm thick on the tray.' },
            { order: 3, instruction: 'Scatter berries and granola evenly over the yogurt.' },
            { order: 4, instruction: 'Melt dark chocolate and drizzle over the top.' },
            { order: 5, instruction: 'Freeze for at least 3 hours until solid. Break into shards and store in a sealed bag in the freezer.' },
        ],
    },
    {
        title: 'Peanut Butter Banana Nice Cream',
        description: 'Creamy one-ingredient banana ice cream blended with peanut butter and vanilla protein — vegan, high-protein, no added sugar.',
        category: 'Dessert',
        prepTime: 5,
        cookTime: 0,
        servings: 2,
        tags: 'Vegan,High-Protein,Frozen,Gluten-Free',
        ingredients: [
            { name: 'Frozen bananas', amount: '3', unit: '' },
            { name: 'Peanut butter', amount: '2', unit: 'tbsp' },
            { name: 'Vanilla protein powder', amount: '20', unit: 'g' },
            { name: 'Almond milk', amount: '30', unit: 'ml' },
            { name: 'Dark chocolate chips', amount: '20', unit: 'g' },
        ],
        steps: [
            { order: 1, instruction: 'Peel and freeze bananas overnight (or at least 4 hours).' },
            { order: 2, instruction: 'Break frozen bananas into chunks and add to a food processor with peanut butter, protein powder, and almond milk.' },
            { order: 3, instruction: 'Process, stopping to scrape down the sides, until smooth and creamy — about 2 minutes.' },
            { order: 4, instruction: 'Eat immediately for soft-serve consistency, or freeze 1 hour for a firmer scoop. Top with dark chocolate chips.' },
        ],
    },
    {
        title: 'Ricotta Lemon Cheesecake Cups',
        description: 'Light, no-bake lemon ricotta dessert cups with a crunchy biscuit base — high-protein, refreshing, and ready in 15 minutes.',
        category: 'Dessert',
        prepTime: 15,
        cookTime: 0,
        servings: 4,
        tags: 'High-Protein,No-Bake,Italian',
        ingredients: [
            { name: 'Ricotta cheese', amount: '400', unit: 'g' },
            { name: 'Digestive biscuits', amount: '100', unit: 'g' },
            { name: 'Butter', amount: '40', unit: 'g' },
            { name: 'Honey', amount: '2', unit: 'tbsp' },
            { name: 'Lemon', amount: '1', unit: '' },
            { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
            { name: 'Fresh blueberries', amount: '100', unit: 'g' },
        ],
        steps: [
            { order: 1, instruction: 'Crush biscuits into fine crumbs. Mix with melted butter and press into the base of 4 serving glasses. Refrigerate.' },
            { order: 2, instruction: 'Beat ricotta with honey, lemon zest, lemon juice, and vanilla until smooth and creamy.' },
            { order: 3, instruction: 'Spoon ricotta mixture on top of the chilled biscuit base.' },
            { order: 4, instruction: 'Top with blueberries and a little extra lemon zest. Refrigerate 30 minutes before serving.' },
        ],
    },
]

async function main() {
    console.log(`Seeding ${recipes.length} additional preset recipes...`)

    let created = 0
    for (const recipe of recipes) {
        await prisma.recipe.create({
            data: {
                title: recipe.title,
                description: recipe.description,
                category: recipe.category,
                prepTime: recipe.prepTime,
                cookTime: recipe.cookTime,
                servings: recipe.servings,
                tags: recipe.tags,
                isPublic: true,
                // userId omitted → defaults to null, making these presets
                ingredients: { create: recipe.ingredients },
                steps: { create: recipe.steps },
            },
        })
        created++
        console.log(`  ✓ ${recipe.title}`)
    }

    console.log(`\nDone! Created ${created} recipes.`)
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
